### ISSUE TITLE
Backend - Epic 1 - User Management and Authentication

### ISSUE THREAD

**Issue by vJechsmayr** [vJechsmayr/Family-Dashboard#2]
# Content of this Epic:
- [ ] Implement user management including registration and login
- [ ] Integrate authentication services (OAuth) for secure login
- [ ] Manage user roles and permissions
- [ ] Integrate Social Login (Github and Google)

**This is an EPIC - It is not able to be assigned to this. If you want to develop some of the features look for the linked issues.**
